/**
 * SECURE BACKEND CONFIGURATION
 *
 * This file is intended for the server-side logic (Node.js).
 * It reads credentials from Environment Variables to ensure security.
 *
 * HOW TO USE:
 * 1. Ensure you have a file named ".env" in your project root.
 * 2. The backend will automatically load these values.
 *
 * WARNING: Never commit the .env file to public version control (GitHub, etc).
 */

export const GHL_CONFIG = {
  // OAUTH CONFIGURATION (REQUIRED)
  // Since your account does not have a Legacy API Key, you MUST use these.
  // Found in marketplace.gohighlevel.com > My Apps
  clientId: process.env.GHL_CLIENT_ID || '',
  clientSecret: process.env.GHL_CLIENT_SECRET || '',

  // The Access Token is generated by exchanging the "code" from the App Installation.
  // Paste the resulting Bearer token here.
  accessToken: process.env.GHL_ACCESS_TOKEN || '',

  // Your Agency Company ID found in GHL Agency Settings > Company
  companyId: process.env.GHL_COMPANY_ID || '',

  // SNAPSHOT CONFIGURATION
  // Maps Subscription Tiers and Industries to specific Snapshot IDs
  snapshotTierMini: process.env.SNAPSHOT_TIER_MINI || '',
  snapshotTierScale: process.env.SNAPSHOT_TIER_SCALE || '',
  snapshotTierMax: process.env.SNAPSHOT_TIER_MAX || '',

  snapshotIndEcommerce: process.env.SNAPSHOT_IND_ECOMMERCE || '',
  snapshotIndSaas: process.env.SNAPSHOT_IND_SAAS || '',
  snapshotIndRealEstate: process.env.SNAPSHOT_IND_REALESTATE || '',

  // (Optional) Specific Location ID if operating on a single sub-account
  locationId: process.env.GHL_LOCATION_ID || '',
};

// Validation Helper
export const validateConfig = () => {
  const missingKeys: string[] = [];

  if (!GHL_CONFIG.clientId) missingKeys.push('GHL_CLIENT_ID');
  if (!GHL_CONFIG.clientSecret) missingKeys.push('GHL_CLIENT_SECRET');
  if (!GHL_CONFIG.companyId) missingKeys.push('GHL_COMPANY_ID');

  if (missingKeys.length > 0) {
    console.error(`❌ CRITICAL ERROR: Missing Environment Variables: ${missingKeys.join(', ')}`);
    console.error('Please ensure your .env file is configured correctly with OAuth Credentials.');
    return false;
  }

  return true;
};
